### ISSUE TITLE
upper bound on mypy dependency

### ISSUE THREAD

**Issue by tgpfeiffer** [gordonbondon/kubernetes-typed#20]
The `setup.py` file declares an upper bound on the `mypy` dependency https://github.com/gordonbondon/kubernetes-typed/blob/82995b008daf551a4fe11660018d9c08c69f9e6e/setup.py#L77
Is there a particular reason for that? Newer versions of mypy often come with good bugfixes, I'd like to use this package with a newer mypy version, if possible.

**Comment by gordonbondon** [comment]
Sorry for the wait, should be fixed now and available in https://pypi.org/project/kubernetes-typed/18.20.1/
