### ISSUE TITLE
Remove (or update) version constraints on mypy

### ISSUE THREAD

**Issue by hansingt** [gordonbondon/kubernetes-typed#22]
Currently, this package depends on [`mypy>=0.800, <=0.910`](https://github.com/gordonbondon/kubernetes-typed/blob/master/setup.py#L77) which makes it impossible to use it with python 3.10+ if you use the `match` Expression, as this has been added in `mypy >= 0.940`.

Why is the version of `mypy` constrained in the `setup.py` anyway? Would it be possible to remove this constaint? Or at least release an updated version?

Thanks in advance!

**Comment by gordonbondon** [comment]
Sorry for the wait, should be fixed now and available in https://pypi.org/project/kubernetes-typed/18.20.1/
